### ISSUE TITLE
Split screen

### ISSUE THREAD

**Issue by CorvetteCole** [AICP/device_motorola_clark#3]
I cannot for the life of me get split screen to activate. Pressing and holding the recent button does literally nothing. Is there a setting I need somewhere?

**Comment by LorDClockaN** [comment]
We have smartbar, not aosp navbar. Go to settings /navbar and add it as a longpress action 
~~ Flowed from my Pixel XL ~~
On Nov 15, 2016 01:25, CorvetteCole notifications@github.com wrote:I cannot for the life of me get split screen to activate. Pressing and holding the recent button does literally nothing. Is there a setting I need somewhere?

**Comment by CorvetteCole** [comment]
Thanks!
